/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.90
 * Generated at: 2023-09-26 13:50:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.NumberFormat;
import java.util.Locale;
import bean.Loaibean;
import bean.ChiTietSizebean;
import bean.Giaybean;
import java.util.ArrayList;
import bean.AdminDangNhapbean;

public final class adminQuanLyMatHang_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.Loaibean");
    _jspx_imports_classes.add("bean.ChiTietSizebean");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("bean.AdminDangNhapbean");
    _jspx_imports_classes.add("bean.Giaybean");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Quản lý mặt hàng</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <a href=\"adminTrangChuController\" class=\"navbar-brand\">Trang chủ</a>\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggler\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse1\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarCollapse1\">\r\n");
      out.write("                <div class=\"navbar-nav\">\r\n");
      out.write("               \r\n");
      out.write("                    <a href=\"adminQuanLyMatHangController\" class=\"nav-item nav-link\">Quản lý mặt hàng</a>\r\n");
      out.write("                    <a href=\"adminXacNhanMuahangController\" class=\"nav-item nav-link\">Xác nhận mua hàng</a>\r\n");
      out.write("                    <a href=\"adminXacNhanHoaDonController\" class=\"nav-item nav-link\">Xác nhận hóa đơn</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"navbar-nav d-flex ms-auto\">\r\n");
      out.write("                ");
AdminDangNhapbean adminbean = (AdminDangNhapbean) session.getAttribute("admin");
                if(adminbean == null){
      out.write("\r\n");
      out.write("               \r\n");
      out.write("                <a href=\"adminDangNhapController\" class=\"nav-item nav-link\">Đăng nhập</a>\r\n");
      out.write("                ");
}else{ 
      out.write("\r\n");
      out.write("                <a href=\"#\" class=\"nav-item nav-link\">");
      out.print(adminbean.getHoTen());
      out.write("</a>\r\n");
      out.write("                <a href=\"adminDangXuatController\" class=\"nav-item nav-link\">Đăng xuất</a>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write(" </nav>\r\n");
      out.write(" \r\n");
      out.write(" <div clas = \"container-fluid\">\r\n");
      out.write(" <div style=\"text-align: center\" class = \"mt-3\"><h3>Quản lý mặt hàng</h3></div>\r\n");
      out.write(" <br>\r\n");

 Giaybean giay = (Giaybean) request.getAttribute("giay");
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action = \"adminQuanLyMatHangController?check=ok\" method=\"post\">\r\n");
      out.write("	<input type = \"submit\" name = \"btnThem\" value = \"Thêm mặt hàng\" class = \"btn btn-outline-dark\">\r\n");
      out.write("</form>\r\n");
      out.write("<div class = \"col-12 row\">\r\n");
      out.write("<div class = \"col-3\"></div>\r\n");

String check = (String) request.getAttribute("check");
if(check != null ){ 
      out.write("\r\n");
      out.write("	<div class = \"col-6\">\r\n");

if(check.equals("ok")){
      out.write("\r\n");
      out.write("	 <form action=\"adminThemMatHangController\" method=\"post\" enctype= \"multipart/form-data\" class = \"p-4\">\r\n");
}else{
      out.write("\r\n");
      out.write("<form action=\"adminSuaMatHangController\" method=\"post\" enctype= \"multipart/form-data\" class = \"p-4\">\r\n");
      out.write("<input name = \"maGiay\" value = \"");
      out.print(giay.getMaGiay());
      out.write("\" style=\"display: none\">\r\n");
} 
      out.write("\r\n");
      out.write("  <div class=\"form-row\">\r\n");
      out.write("    <div class=\"form-group col-12\">\r\n");
      out.write("      <label>Tên hàng</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name = \"txtTenHang\" value = \"");
      out.print(giay!= null ? giay.getTenGiay() : "");
      out.write("\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("    <div class=\"form-group col-12\">\r\n");
      out.write("      <label>Giá</label>\r\n");
      out.write("      <input type=\"number\" min = \"0\" class=\"form-control\" name = \"txtGia\" value = \"");
      out.print(giay != null ? giay.getGia() : "");
      out.write("\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group col-12\">\r\n");
      out.write("    <label>Số lượng</label>\r\n");
      out.write("    <input type=\"number\" min = \"1\" class=\"form-control\"  name = \"txtSoLuong\" value = \"");
      out.print(giay != null ? giay.getSoLuongTon() : "");
      out.write("\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <br>\r\n");
      out.write("      <div class=\"form-group col-12\">\r\n");
      out.write("      <label>Màu sắc</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name = \"txtMauSac\" value = \"");
      out.print(giay != null ? giay.getMauGiay() : "");
      out.write("\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("  <div class=\"form-group col-12\">\r\n");
      out.write("    <label>Ảnh </label>\r\n");
      out.write("   	");
if(giay != null){ 
      out.write("\r\n");
      out.write("   	<div style=\"width: 100px; height: 100px\"><img src=\"");
      out.print(giay.getAnh());
      out.write("\" style=\"width: 100%; height: 100%\"></div>\r\n");
      out.write("   	<input type=\"text\" name=\"txtanh\" value = \"");
      out.print(giay.getAnh());
      out.write("\">\r\n");
      out.write("   	");
} 
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("    <input type=\"file\" name=\"txtfile\" value = \"");
      out.print(giay != null ? giay.getAnh() : "");
      out.write("\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <br>\r\n");
      out.write("  <div class=\"form-row\">\r\n");
      out.write("    <div class=\"form-group col-12\">\r\n");
      out.write("      <labe>Tên loại</label>\r\n");
      out.write("      <select class=\"form-control\" name=\"txtMaLoai\">\r\n");
      out.write("      ");
if(request.getAttribute("dsLoai") != null){
    	  ArrayList<Loaibean> dsLoai = (ArrayList<Loaibean>) request.getAttribute("dsLoai");
    	  for(Loaibean loai : dsLoai){
    	 	if(giay != null && giay.getMaLoai() == loai.getMaLoai()){
    	  
      out.write("\r\n");
      out.write("    	  	<option value = ");
      out.print(loai.getMaLoai() );
      out.write(" selected>");
      out.print(loai.getTenLoai());
      out.write("</option>\r\n");
      out.write("    		");
} 
      out.write("\r\n");
      out.write("    	  <option value = ");
      out.print(loai.getMaLoai() );
      out.write('>');
      out.print(loai.getTenLoai());
      out.write("</option>\r\n");
      out.write("      ");
}} 
      out.write("\r\n");
      out.write("      </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group col-12\">\r\n");
      out.write("      <label>Size</label>\r\n");
      out.write("      \r\n");
      out.write("      <div class = \"row\">\r\n");
      out.write("      ");

      
      if(request.getAttribute("dsCTS") != null){
      ArrayList<Integer> dsCTSize = (ArrayList<Integer>) request.getAttribute("dsCTS");
      ArrayList<Integer> sizeCuaHang = (ArrayList<Integer>) request.getAttribute("sizeCuaHang");
      int n = dsCTSize.size();
      	for(int i = 0; i < n; i++){
      out.write("\r\n");
      out.write("      		<div class = \"col-1\"><input type=\"checkbox\" name = \"txtSize\" value = \"");
      out.print(dsCTSize.get(i));
      out.write("\"\r\n");
      out.write("      		");
if(sizeCuaHang != null){
      		int m = sizeCuaHang.size();
      			for(int j =0; j<m; j++){
      				if(sizeCuaHang.get(j) == dsCTSize.get(i)){
      		
      out.write("\r\n");
      out.write("      		checked\r\n");
      out.write("      		");
}}} 
      out.write("\r\n");
      out.write("      		></div>\r\n");
      out.write("      		<div class = \"col-2\"><p>");
      out.print(dsCTSize.get(i));
      out.write("</p></div>\r\n");
      out.write("      	");
}}
      
      
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <br>\r\n");
      out.write("\r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-outline-dark\">Xác nhận</button>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
} 
      out.write("\r\n");
      out.write(" 	<div class = \"col-3\" style=\"padding: 0px 0px !important\"></div>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	\r\n");
      out.write(" 	<table class = \"table\">\r\n");
      out.write(" 		<thead class = \"table-dark\">\r\n");
      out.write(" 		<tr>\r\n");
      out.write(" 			<th scope=\"col\">Ảnh</th>\r\n");
      out.write(" 			<th scope=\"col\">Tên giày</th>\r\n");
      out.write("      		<th scope=\"col\">Giá</th>\r\n");
      out.write("      		<th scope=\"col\">Tên loại</th>\r\n");
      out.write("      		<th scope=\"col\">Màu sắc</th>\r\n");
      out.write("      		<th scope=\"col\">Số lượng</th>\r\n");
      out.write("      		<th scope=\"col\">Sửa</th>\r\n");
      out.write("      		<th scope=\"col\">Xóa</th>\r\n");
      out.write(" 		</tr>\r\n");
      out.write(" 		</thead>\r\n");
      out.write(" 	<tbody>\r\n");
      out.write(" 	");
ArrayList<Giaybean> dsGiay = (ArrayList<Giaybean>) request.getAttribute("dsGiay");
 	Locale localeVN = new Locale("vi", "VN");
    NumberFormat vn = NumberFormat.getInstance(localeVN);
 		for(Giaybean g : dsGiay){
      out.write("\r\n");
      out.write(" 		<tr>\r\n");
      out.write(" 			<th scope=\"row\"><img src=\"");
      out.print(g.getAnh());
      out.write("\" style=\"width: 50px; height: 50px\"></th>\r\n");
      out.write(" 			<td>");
      out.print(g.getTenGiay() );
      out.write("</td>\r\n");
      out.write("      		<td>");
      out.print(vn.format(g.getGia()));
      out.write("đ</td>\r\n");
      out.write("      		<td>");
      out.print(g.getMaGiay() );
      out.write("</td>\r\n");
      out.write("      		<td>");
      out.print(g.getMauGiay() );
      out.write("</td>\r\n");
      out.write("      		<td>");
      out.print(g.getSoLuongTon() );
      out.write("</td>\r\n");
      out.write("      		<td><a href=\"adminQuanLyMatHangController?maGiay=");
      out.print(g.getMaGiay());
      out.write("&check=sua\" class = \"btn btn-outline-dark\">\r\n");
      out.write("      		<i class=\"bi bi-pencil-square\"></i></a>\r\n");
      out.write("      		</td>\r\n");
      out.write("      		<td><a href=\"adminXoaMatHangController?maGiay=");
      out.print(g.getMaGiay());
      out.write("\" class = \"btn btn-outline-dark\"><i class=\"bi bi-trash\"></i></a></td>\r\n");
      out.write(" 		</tr>\r\n");
      out.write(" 		");
} 
      out.write("\r\n");
      out.write(" 	</tbody>\r\n");
      out.write(" 	</table>\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
