/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.90
 * Generated at: 2023-08-27 02:52:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.GioHangbean;
import java.text.NumberFormat;
import java.util.Locale;
import bean.KhachHangbean;
import bean.Giaybean;
import bean.Loaibean;
import java.util.ArrayList;

public final class trangChu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.KhachHangbean");
    _jspx_imports_classes.add("bean.Loaibean");
    _jspx_imports_classes.add("bean.GioHangbean");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("bean.Giaybean");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("	/* Custom style */\r\n");
      out.write("    .navbar{\r\n");
      out.write("        margin-bottom: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("    .hover-div:hover{\r\n");
      out.write("	border: 1px solid #dcdcdc !important;\r\n");
      out.write("	box-shadow: 5px 5px 5px 5px #dcdcdc !important;	\r\n");
      out.write("}\r\n");
      out.write(".image img {\r\n");
      out.write("\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 300;\r\n");
      out.write("    transition: all 1s ease-in-out\r\n");
      out.write("}\r\n");
      out.write(".image-2{\r\n");
      out.write("	 overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".image:hover img {\r\n");
      out.write("    transform: scale(1.25);\r\n");
      out.write("   \r\n");
      out.write("    cursor: pointer\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 780px) {\r\n");
      out.write("	.danhMucHai {\r\n");
      out.write("		display: none\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 781px){\r\n");
      out.write("	.danhMuc{\r\n");
      out.write("		display: none\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>Trang chủ</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <a href=\"trangChuController\" class=\"navbar-brand\">Trang chủ</a>\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggler\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse1\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarCollapse1\">\r\n");
      out.write("                <div class=\"navbar-nav\">\r\n");
      out.write("                \r\n");
      out.write("                ");

                //số lượng giỏ
                	ArrayList<GioHangbean> dsGio = (ArrayList<GioHangbean>) session.getAttribute("dsGioHang");
                	int n = 0;
                		if(dsGio != null)
                			n = dsGio.size();
                	
      out.write("\r\n");
      out.write("                    <a href=\"gioHangController\" class=\"nav-item nav-link\">Giỏ hàng(");
      out.print(n );
      out.write(")</a>\r\n");
      out.write("                    <a href=\"lichSuController\" class=\"nav-item nav-link\">Lịch sử mua hàng</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form class=\"d-flex mx-auto\" action=\"trangChuController\" method=\"post\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control me-sm-2\" style=\"width: 300px\" placeholder=\"Search\" name = \"txtTimKiem\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-outline-light\">Search</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <div class=\"navbar-nav\">\r\n");
      out.write("                ");
KhachHangbean khbean = (KhachHangbean) session.getAttribute("khachHang");
                if(khbean == null){
      out.write("\r\n");
      out.write("                <a href=\"dangKyController\" class=\"nav-item nav-link\">Đăng ký</a>\r\n");
      out.write("                <a href=\"dangNhapController\" class=\"nav-item nav-link\">Đăng nhập</a>\r\n");
      out.write("                ");
}else{ 
      out.write("\r\n");
      out.write("                <a href=\"hoSoController?hoSo=");
      out.print(khbean.getMaKhachHang());
      out.write("\" class=\"nav-item nav-link\">");
      out.print(khbean.getHoTen());
      out.write("</a>\r\n");
      out.write("                <a href=\"dangXuatController\" class=\"nav-item nav-link\">Đăng xuất</a>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write(" \r\n");
      out.write("	\r\n");
      out.write("	<div class = \"container\">\r\n");
      out.write("		<div class = \"row\">\r\n");
      out.write("	<div class = \"col-md-3 col-12 col-sm-3 danhMuc\" style=\"overflow-y: scroll; height: 100vh \">\r\n");
      out.write("	<h3>THƯƠNG HIỆU</h3>\r\n");
      out.write("	<div class = \"btn-group\">\r\n");
      out.write("	<div class = \"row\">\r\n");
      out.write("	");

	// đổ ra danh sách loại
	 ArrayList<Loaibean> dsLoai = (ArrayList<Loaibean>) request.getAttribute("dsLoai");
	for(Loaibean loai: dsLoai){ 
      out.write("\r\n");
      out.write("	<div style=\"margin: 5px 0\" class = \"col-12\">\r\n");
      out.write("	<a href=\"trangChuController?maLoai=");
      out.print(loai.getMaLoai());
      out.write("&tenLoai=");
      out.print(loai.getTenLoai() );
      out.write("\" style=\"width: 90%\" class=\"text-decoration-none btn btn-outline-dark\">");
      out.print(loai.getTenLoai().toUpperCase());
      out.write("</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<h3>SIZE</h3>\r\n");
      out.write("	<div class = \"row\">\r\n");
      out.write("		<div class = \"btn-group flex-wrap\">\r\n");
      out.write("	");
ArrayList<Integer> dsSize = (ArrayList<Integer>) request.getAttribute("dsSize");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
for(int size : dsSize){
		//đổ ra danh sách size
	
      out.write("\r\n");
      out.write("	<div class = \"col-lg-3 col-md-4 col-sm-4 col-2 \" > \r\n");
      out.write("	\r\n");
      out.write("	<a href=\"trangChuController?size=");
      out.print(size);
      out.write("\" class=\"text-decoration-none btn btn-outline-dark\" style=\"margin: 5px 5px 5px 0; width: 90%; height: 90%\">\r\n");
      out.write("	<span style=\"justify-content: center; align-content: center; width: 100%; display: flex\">");
      out.print(size );
      out.write("</span>\r\n");
      out.write("	</a>	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	<h3>MÀU SẮC</h3>\r\n");
      out.write("	\r\n");
      out.write("	<div class = \"btn-group\">\r\n");
      out.write("	<div class = \"row\">\r\n");
      out.write("		");
ArrayList<String> dsMauGiay =(ArrayList<String>) request.getAttribute("dsMauGiay");
		for(String mau : dsMauGiay){
		//đổ ra danh sách màu
		
      out.write("\r\n");
      out.write("		<div class = \"col-12\">\r\n");
      out.write("			<a href=\"trangChuController?mau=");
      out.print(mau);
      out.write("\" class=\"text-decoration-none btn btn-outline-dark\" style=\"width: 90%; margin: 5px 0;\">");
      out.print(mau );
      out.write("</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</div> \r\n");
      out.write("	</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	<div class = \"danhMucHai\">\r\n");
      out.write("	<a class=\"btn btn-outline-dark danhMucHai\" data-bs-toggle=\"collapse\" href=\"#collapseExample3\" role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseExample3\" style=\"width: 100%\">\r\n");
      out.write("    Danh mục\r\n");
      out.write("  </a>\r\n");
      out.write("	<div class = \"col-12 collapse\" id=\"collapseExample3\">\r\n");
      out.write("	<h3>THƯƠNG HIỆU</h3>\r\n");
      out.write("	<div class = \"btn-group flex-wrap\">\r\n");
      out.write("	<div class = \"row\">\r\n");
      out.write("	");

	 ArrayList<Loaibean> dsLoai1 = (ArrayList<Loaibean>) request.getAttribute("dsLoai");
	for(Loaibean loai: dsLoai1){ 
      out.write("\r\n");
      out.write("	<div class = \"col-lg-2 col-md-4 col-sm-4 col-4\">\r\n");
      out.write("	<a href=\"trangChuController?maLoai=");
      out.print(loai.getMaLoai());
      out.write("&tenLoai=");
      out.print(loai.getTenLoai() );
      out.write("\" style=\"width: 80%;margin: 5px 5px\" class=\"text-decoration-none btn btn-outline-dark\">");
      out.print(loai.getTenLoai().toUpperCase());
      out.write("</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<h3>SIZE</h3>\r\n");
      out.write("	<div class = \"row\">\r\n");
      out.write("	<div class = \"btn-group flex-wrap\">\r\n");
      out.write("	");
ArrayList<Integer> dsSize1 = (ArrayList<Integer>) request.getAttribute("dsSize");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
for(int size : dsSize1){
	
      out.write("\r\n");
      out.write("	<div class = \"col-lg-2 col-md-3 col-sm-4 col-2 \" > \r\n");
      out.write("	\r\n");
      out.write("	<a href=\"trangChuController?size=");
      out.print(size);
      out.write("\" class=\"text-decoration-none btn btn-outline-dark\" style=\"margin: 5px 5px 5px 0; width: 90%; height: 90%\">\r\n");
      out.write("	<span style=\"justify-content: center; align-content: center; width: 100%; display: flex\">");
      out.print(size );
      out.write("</span>\r\n");
      out.write("	</a>\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	<h3>MÀU SẮC</h3>\r\n");
      out.write("	<div class = \"btn-group\">\r\n");
      out.write("	<div class = \"row\"> \r\n");
      out.write("		");
ArrayList<String> dsMauGiay1 =(ArrayList<String>) request.getAttribute("dsMauGiay");
		for(String mau : dsMauGiay1){
      out.write("\r\n");
      out.write("		<div class = \"col-lg-2 col-md-3 col-sm-3 col-3\">\r\n");
      out.write("			<a href=\"trangChuController?mau=");
      out.print(mau);
      out.write("\" class=\"text-decoration-none btn btn-outline-dark\" style=\"width: 80% ;margin: 5px 0;\">");
      out.print(mau );
      out.write("</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div class = \"col-lg-9 col-md-9 col-12 col-sm-12\">\r\n");
      out.write("		<div class = \"row\">\r\n");
      out.write("		");
if(request.getAttribute("tieuDe") != null){
      out.write("\r\n");
      out.write("			<div><h3>");
      out.print(request.getAttribute("tieuDe") );
      out.write("</h3></div>\r\n");
      out.write("		");
}
      out.write("\r\n");
      out.write("		");
Locale localeVN = new Locale("vi", "VN");
	    NumberFormat vn = NumberFormat.getInstance(localeVN);
		
		ArrayList<Giaybean> dsGiay = (ArrayList<Giaybean>) request.getAttribute("dsGiay");
			for(Giaybean giay: dsGiay){
      out.write("\r\n");
      out.write("			\r\n");
      out.write("				<div class = \"col-lg-3 col-md-4 col-sm-4 col-4 shadow-sm p-3 mb-5 bg-white rounded hover-div image\">\r\n");
      out.write("				\r\n");
      out.write("				<a href=\"matHangController?maGiay=");
      out.print(giay.getMaGiay());
      out.write("\">\r\n");
      out.write("				<div class = \"image-2\">\r\n");
      out.write("					<img src=\"");
      out.print(giay.getAnh());
      out.write("\" width=\"300\" height=\"300\" class = \"img-thumbnail\">\r\n");
      out.write("				</div><br>\r\n");
      out.write("				<label style=\"font-weight: bold; color: black\">");
      out.print(giay.getTenGiay());
      out.write("</label><br>\r\n");
      out.write("				\r\n");
      out.write("				<label style=\"color: black\">Giá: ");
      out.print(vn.format(giay.getGia()));
      out.write("đ</label><br>\r\n");
      out.write("				");
if(giay.getSoLuongTon() != 0){ 
      out.write("\r\n");
      out.write("				<label style=\"color: grey\">Số lượng còn: ");
      out.print(giay.getSoLuongTon());
      out.write("</label><br>\r\n");
      out.write("				");
}else{ 
      out.write("\r\n");
      out.write("				<label style=\"color: grey\">Đã hết hàng</label><br>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				</a>\r\n");
      out.write("			\r\n");
      out.write("			</div>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
